# Nafisur Rahman
nafisur21@gmail.com<br>
https://www.linkedin.com/in/nafisur-rahman

# Titanic Survival
Predict who survived the titanic disaster
## Part 2

# Machine Learning

### About this project
The Titanic dataset provides observations for each passenger and the survival outcome. The problem statement entails predicting whether a passenger would survive or not survive given the features such as passenger class, sex, fare, age, number of
siblings/spouse aboard, number of parents/children aboard, and others.<br>
The task is about understanding the Titanic Disaster with the help of Data Visualization and building a model that can predict the Survival of the Passengers of Titanic using Machine Learning.

## A. Importing Library

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import IPython
from IPython import display

#ignore warnings
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline
pd.set_option('display.max_columns', 100)

## B. Loading Processed dataset

In [2]:
train_processed=pd.read_csv("Processed_data/train_processed.csv",index_col='PassengerId')
test_processed=pd.read_csv("Processed_data/test_processed.csv",index_col='PassengerId')

In [3]:
train_processed.head()

Survived   Age     Fare  FamilySize  IsMother  IsMale  Deck_A  \
PassengerId                                                                  
1                   0  22.0   7.2500           2         0       1       0   
2                   1  38.0  71.2833           2         0       0       0   
3                   1  26.0   7.9250           1         0       0       0   
4                   1  35.0  53.1000           2         0       0       0   
5                   0  35.0   8.0500           1         0       1       0   

             Deck_B  Deck_C  Deck_D  Deck_E  Deck_F  Deck_G  Deck_Z  Pclass_1  \
PassengerId                                                                     
1                 0       0       0       0       0       0       1         0   
2                 0       1       0       0       0       0       0         1   
3                 0       0       0       0       0       0       1         0   
4                 0       1       0       0       0       0       0         1   
5                 0       0       0       0       0       0       1         0   

             Pclass_2  Pclass_3  Title_Lady  Title_Master  Title_Miss  \
PassengerId                                                             
1                   0         1           0             0           0   
2                   0         0           0             0           0   
3                   0         1           0             0           1   
4                   0         0           0             0           0   
5                   0         1           0             0           0   

             Title_Mr  Title_Mrs  Title_Officer  Title_Sir  Fare_Bin_very_low  \
PassengerId                                                                     
1                   1          0              0          0                  1   
2                   0          1              0          0                  0   
3                   0          0              0          0                  0   
4                   0          1              0          0                  0   
5                   1          0              0          0                  0   

             Fare_Bin_low  Fare_Bin_high  Fare_Bin_very_high  Embarked_C  \
PassengerId                                                                
1                       0              0                   0           0   
2                       0              0                   1           1   
3                       1              0                   0           0   
4                       0              0                   1           0   
5                       1              0                   0           0   

             Embarked_Q  Embarked_S  AgeState_Adult  AgeState_Child  
PassengerId                                                          
1                     0           1               1               0  
2                     0           0               1               0  
3                     0           1               1               0  
4                     0           1               1               0  
5                     0           1               1               0

In [4]:
train_processed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [5]:
test_processed.head()

Age     Fare  FamilySize  IsMother  IsMale  Deck_A  Deck_B  \
PassengerId                                                                
892          34.5   7.8292           1         0       1       0       0   
893          47.0   7.0000           2         0       0       0       0   
894          62.0   9.6875           1         0       1       0       0   
895          27.0   8.6625           1         0       1       0       0   
896          22.0  12.2875           3         1       0       0       0   

             Deck_C  Deck_D  Deck_E  Deck_F  Deck_G  Deck_Z  Pclass_1  \
PassengerId                                                             
892               0       0       0       0       0       1         0   
893               0       0       0       0       0       1         0   
894               0       0       0       0       0       1         0   
895               0       0       0       0       0       1         0   
896               0       0       0       0       0       1         0   

             Pclass_2  Pclass_3  Title_Lady  Title_Master  Title_Miss  \
PassengerId                                                             
892                 0         1           0             0           0   
893                 0         1           0             0           0   
894                 1         0           0             0           0   
895                 0         1           0             0           0   
896                 0         1           0             0           0   

             Title_Mr  Title_Mrs  Title_Officer  Title_Sir  Fare_Bin_very_low  \
PassengerId                                                                     
892                 1          0              0          0                  1   
893                 0          1              0          0                  1   
894                 1          0              0          0                  0   
895                 1          0              0          0                  0   
896                 0          1              0          0                  0   

             Fare_Bin_low  Fare_Bin_high  Fare_Bin_very_high  Embarked_C  \
PassengerId                                                                
892                     0              0                   0           0   
893                     0              0                   0           0   
894                     1              0                   0           0   
895                     1              0                   0           0   
896                     1              0                   0           0   

             Embarked_Q  Embarked_S  AgeState_Adult  AgeState_Child  
PassengerId                                                          
892                   1           0               1               0  
893                   0           1               1               0  
894                   1           0               1               0  
895                   0           1               1               0  
896                   0           1               1               0

In [6]:
test_processed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

## C. Dataset in numpy ndarray format
For doing machine learning analysis, we have to convert the DataFrame into numpy matrix of features and output column as numpy array.

In [7]:
X_train_processed=train_processed.iloc[:,1:].values.astype('float')
X_train_processed.shape

(891, 32)

In [8]:
y_train_processed=train_processed.iloc[:,0].values
y_train_processed.shape

(891,)

In [9]:
X_test_processed=test_processed.iloc[:,0:].values.astype('float')
X_test_processed.shape

(418, 32)

Features Matrix X

In [10]:
X=X_train_processed
X

array([[ 22.    ,   7.25  ,   2.    , ...,   1.    ,   1.    ,   0.    ],
       [ 38.    ,  71.2833,   2.    , ...,   0.    ,   1.    ,   0.    ],
       [ 26.    ,   7.925 ,   1.    , ...,   1.    ,   1.    ,   0.    ],
       ..., 
       [ 22.    ,  23.45  ,   4.    , ...,   1.    ,   1.    ,   0.    ],
       [ 26.    ,  30.    ,   1.    , ...,   0.    ,   1.    ,   0.    ],
       [ 32.    ,   7.75  ,   1.    , ...,   0.    ,   1.    ,   0.    ]])

Output/Dependent Variable y

In [11]:
y=y_train_processed
y.shape

(891,)

## D. Splitting data into Training and Test set
We split the data into training and test sets using an 80/20 split.

In [12]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [13]:
# average survival in train and test
print('mean survival in train : {0:.3f}'.format(np.mean(y_train)))
print('mean survival in test : {0:.3f}'.format(np.mean(y_test)))

mean survival in train : 0.383
mean survival in test : 0.385


## E. Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)
X_test_processed_sc=sc.transform(X_test_processed)

## Machine Learning Models
1. Baseline Model
2. Logistic Regression
3. 


### 1. Baseline Model: DummyClassifier

In [15]:
from sklearn.dummy import DummyClassifier as dc

In [16]:
model_dummy=dc(strategy='most_frequent',random_state=0)
model_dummy.fit(X_train,y_train)
y_pred_dummy=model_dummy.predict(X_test)
print('accuracy for baseline model :',accuracy_score(y_test,y_pred_dummy))
print('confusion matrix for baseline model:\n',confusion_matrix(y_test,y_pred_dummy))
print('F1 score for baseline model :',f1_score(y_test,y_pred_dummy))
print('Precision score for baseline model :',precision_score(y_test,y_pred_dummy))
print('recall score for baseline model :',recall_score(y_test,y_pred_dummy))

accuracy for baseline model : 0.614525139665
confusion matrix for baseline model:
 [[110   0]
 [ 69   0]]
F1 score for baseline model : 0.0
Precision score for baseline model : 0.0
recall score for baseline model : 0.0


### 2. Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression as lr

In [18]:
model_lr=lr(random_state=0)


In [19]:
#help(model_lr)

Applying Grid Search to find the best parameters

In [20]:
%%time
from sklearn.model_selection import GridSearchCV
parameters = {'C':[0.5,1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' : ['l1','l2']}
grid_search = GridSearchCV(estimator = model_lr,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train_sc, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best Accuracy :',best_accuracy)
print('Best parameters:\n',best_parameters)

Best Accuracy : 0.827247191011
Best parameters:
 {'C': 1.0, 'penalty': 'l1'}
Wall time: 7.01 s


In [21]:
%%time
model_lr=lr(penalty='l2',C=1.0,random_state=0)
model_lr.fit(X_train_sc,y_train)
y_pred_lr=model_lr.predict(X_test_sc)
print('accuracy for Logistic Regression :',accuracy_score(y_test,y_pred_lr))
print('confusion matrix for Logistic Regression:\n',confusion_matrix(y_test,y_pred_lr))
print('F1 score for Logistic Regression :',f1_score(y_test,y_pred_lr))
print('Precision score for Logistic Regression :',precision_score(y_test,y_pred_lr))
print('recall score for Logistic Regression :',recall_score(y_test,y_pred_lr))

accuracy for Logistic Regression : 0.843575418994
confusion matrix for Logistic Regression:
 [[96 14]
 [14 55]]
F1 score for Logistic Regression : 0.797101449275
Precision score for Logistic Regression : 0.797101449275
recall score for Logistic Regression : 0.797101449275
Wall time: 52.6 ms


### 3. K-Nearest Neighbors (K-NN) Classifier

In [22]:
from sklearn.neighbors import KNeighborsClassifier as knn

In [23]:
model_knn=knn()

In [24]:
#help(model_knn)

In [25]:
%%time
from sklearn.model_selection import GridSearchCV
parameters = {'n_neighbors':[5,6,7], 'weights' : ['uniform','distance'],'algorithm':['auto'],
              'leaf_size':[5,10],'p':[1,2],'metric':['minkowski']}
grid_search = GridSearchCV(estimator = model_knn,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train_sc, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best Accuracy :',best_accuracy)
print('Best parameters:\n',best_parameters)

Best Accuracy : 0.818820224719
Best parameters:
 {'algorithm': 'auto', 'leaf_size': 5, 'metric': 'minkowski', 'n_neighbors': 6, 'p': 1, 'weights': 'uniform'}
Wall time: 15.3 s


In [26]:
%%time
model_knn=knn(algorithm='auto',leaf_size=10,metric='minkowski',n_neighbors=5,p=1,weights='uniform')
model_knn.fit(X_train_sc,y_train)
y_pred_knn=model_knn.predict(X_test_sc)
print('accuracy for K-Nearest Neighbors Classifier :',accuracy_score(y_test,y_pred_knn))
print('confusion matrix for K-Nearest Neighbors Classifier:\n',confusion_matrix(y_test,y_pred_knn))
print('F1 score for K-Nearest Neighbors Classifier :',f1_score(y_test,y_pred_knn))
print('Precision score for K-Nearest Neighbors Classifier :',precision_score(y_test,y_pred_knn))
print('recall score for K-Nearest Neighbors Classifier :',recall_score(y_test,y_pred_knn))

accuracy for K-Nearest Neighbors Classifier : 0.849162011173
confusion matrix for K-Nearest Neighbors Classifier:
 [[102   8]
 [ 19  50]]
F1 score for K-Nearest Neighbors Classifier : 0.787401574803
Precision score for K-Nearest Neighbors Classifier : 0.862068965517
recall score for K-Nearest Neighbors Classifier : 0.724637681159
Wall time: 68 ms


### 4. Support Vector Machine (SVM)

In [27]:
from sklearn.svm import SVC

In [28]:
model_svm=SVC(random_state=0)

In [29]:
#help(model_svm)

In [30]:
%%time
from sklearn.model_selection import GridSearchCV
parameters = {'C': [0.5,1,1.5,2], 'kernel': ['rbf'], 'gamma': [0.05,0.1,0.15],
              'degree':[1,2,3]}
grid_search = GridSearchCV(estimator = model_svm,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train_sc, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best Accuracy :',best_accuracy)
print('Best parameters:\n',best_parameters)

Best Accuracy : 0.830056179775
Best parameters:
 {'C': 1.5, 'degree': 1, 'gamma': 0.05, 'kernel': 'rbf'}
Wall time: 15.6 s


In [31]:
%%time
model_svm=SVC(C=1.5,degree=1,gamma=0.05,kernel='rbf',random_state=0)
model_svm.fit(X_train_sc,y_train)
y_pred_svm=model_svm.predict(X_test_sc)
print('accuracy for SVM Classifier :',accuracy_score(y_test,y_pred_svm))
print('confusion matrix for SVM Classifier:\n',confusion_matrix(y_test,y_pred_svm))
print('F1 score for SVM Classifier :',f1_score(y_test,y_pred_svm))
print('Precision score for SVM Classifier :',precision_score(y_test,y_pred_svm))
print('recall score for SVM Classifier :',recall_score(y_test,y_pred_svm))

accuracy for SVM Classifier : 0.815642458101
confusion matrix for SVM Classifier:
 [[100  10]
 [ 23  46]]
F1 score for SVM Classifier : 0.736
Precision score for SVM Classifier : 0.821428571429
recall score for SVM Classifier : 0.666666666667
Wall time: 103 ms


### 5. Naive Bayes Classifier

In [32]:
from sklearn.naive_bayes import GaussianNB

In [33]:
model_nb=GaussianNB()

In [34]:
%%time

model_nb.fit(X_train,y_train)
y_pred_nb=model_nb.predict(X_test)
print('accuracy for Naive Bayes Classifier :',accuracy_score(y_test,y_pred_nb))
print('confusion matrix for Naive Bayes Classifier:\n',confusion_matrix(y_test,y_pred_nb))
print('F1 score for Naive Bayes Classifier :',f1_score(y_test,y_pred_nb))
print('Precision score for Naive Bayes Classifier :',precision_score(y_test,y_pred_nb))
print('recall score for Naive Bayes Classifier :',recall_score(y_test,y_pred_nb))

accuracy for Naive Bayes Classifier : 0.798882681564
confusion matrix for Naive Bayes Classifier:
 [[97 13]
 [23 46]]
F1 score for Naive Bayes Classifier : 0.71875
Precision score for Naive Bayes Classifier : 0.779661016949
recall score for Naive Bayes Classifier : 0.666666666667
Wall time: 29.5 ms


### 6. Decision Tree Classifier

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
model_dt=DecisionTreeClassifier(random_state=0)

In [37]:
#help(model_dt)

In [38]:
%%time
from sklearn.model_selection import GridSearchCV
parameters = {'criterion': ["gini","entropy"], 'max_depth': [3,5,7,10], 'min_samples_split': [2,5],
              'min_samples_leaf':[1,2,3],'min_impurity_decrease':[0,0.1,0.2],'min_impurity_split':[0,0.05,0.1,0.2]}
grid_search = GridSearchCV(estimator = model_dt,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best Accuracy :',best_accuracy)
print('Best parameters:\n',best_parameters)

Best Accuracy : 0.837078651685
Best parameters:
 {'criterion': 'gini', 'max_depth': 3, 'min_impurity_decrease': 0, 'min_impurity_split': 0.2, 'min_samples_leaf': 1, 'min_samples_split': 2}
Wall time: 27.7 s


In [46]:
%%time
model_dt=DecisionTreeClassifier(criterion='gini',max_depth=6,random_state=0)
model_dt.fit(X_train,y_train)
y_pred_dt=model_dt.predict(X_test)
print('accuracy for Decission Tree Classifier :',accuracy_score(y_test,y_pred_dt))
print('confusion matrix for Decission Tree Classifier:\n',confusion_matrix(y_test,y_pred_dt))
print('F1 score for Decission Tree Classifier :',f1_score(y_test,y_pred_dt))
print('Precision score for Decission Tree Classifier :',precision_score(y_test,y_pred_dt))
print('recall score for Decission Tree Classifier :',recall_score(y_test,y_pred_dt))

accuracy for Decission Tree Classifier : 0.798882681564
confusion matrix for Decission Tree Classifier:
 [[96 14]
 [22 47]]
F1 score for Decission Tree Classifier : 0.723076923077
Precision score for Decission Tree Classifier : 0.770491803279
recall score for Decission Tree Classifier : 0.68115942029
Wall time: 28 ms


### 7. Random Forest

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
model_rf=RandomForestClassifier(random_state=0)

In [49]:
#help(model_rf)

In [51]:
%%time
from sklearn.model_selection import GridSearchCV
parameters = {'n_estimators':[100,200],'criterion':['entropy','gini'],
              'min_samples_leaf':[2,5,7],
              'max_depth':[5,6,7]
               }
grid_search = GridSearchCV(estimator = model_rf,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best Accuracy :',best_accuracy)
print('Best parameters:\n',best_parameters)

Best Accuracy : 0.838483146067
Best parameters:
 {'criterion': 'gini', 'max_depth': 6, 'min_samples_leaf': 2, 'n_estimators': 100}
Wall time: 1min 35s


In [52]:
%%time
model_rf=RandomForestClassifier(n_estimators=100,max_depth=6,criterion='entropy',min_samples_leaf=3,max_features=9,
                                min_samples_split=2,min_impurity_decrease=0,random_state=0)
model_rf.fit(X_train,y_train)
y_pred_rf=model_rf.predict(X_test)
print('accuracy for Random Forest Classifier :',accuracy_score(y_test,y_pred_rf))
print('confusion matrix for Random Forest Classifier:\n',confusion_matrix(y_test,y_pred_rf))
print('F1 score for Random Forest Classifier :',f1_score(y_test,y_pred_rf))
print('Precision score for Random Forest Classifier :',precision_score(y_test,y_pred_rf))
print('recall score for Random Forest Classifier :',recall_score(y_test,y_pred_rf))

accuracy for Random Forest Classifier : 0.849162011173
confusion matrix for Random Forest Classifier:
 [[101   9]
 [ 18  51]]
F1 score for Random Forest Classifier : 0.790697674419
Precision score for Random Forest Classifier : 0.85
recall score for Random Forest Classifier : 0.739130434783
Wall time: 638 ms


### 8. XGBoost

In [53]:
import xgboost

In [54]:
from xgboost import XGBClassifier

In [55]:
model_xgb=XGBClassifier(max_depth=3, learning_rate=0.1, n_estimators=100, silent=True, 
                        objective='binary:logistic', nthread=-1, gamma=0, min_child_weight=1, max_delta_step=0, 
                        subsample=1, colsample_bytree=1, colsample_bylevel=1, reg_alpha=0, reg_lambda=1, 
                        scale_pos_weight=1, base_score=0.5, seed=0, missing=None)

In [56]:
%%time
model_xgb=XGBClassifier(max_depth=3, learning_rate=0.09, n_estimators=200, silent=True, 
                        objective='binary:logistic', nthread=-1, gamma=0, min_child_weight=1, max_delta_step=0, 
                        subsample=1, colsample_bytree=1, colsample_bylevel=1, reg_alpha=0, reg_lambda=1, 
                        scale_pos_weight=1, base_score=0.5, seed=0, missing=None)
model_xgb.fit(X_train,y_train)
y_pred_xgb=model_xgb.predict(X_test)
print('accuracy for XGBoost Classifier :',accuracy_score(y_test,y_pred_xgb))
print('confusion matrix for XGBoost Classifier:\n',confusion_matrix(y_test,y_pred_xgb))
print('F1 score for XGBoost Classifier :',f1_score(y_test,y_pred_xgb))
print('Precision score for XGBoost Classifier :',precision_score(y_test,y_pred_xgb))
print('recall score for XGBoost Classifier :',recall_score(y_test,y_pred_xgb))

accuracy for XGBoost Classifier : 0.860335195531
confusion matrix for XGBoost Classifier:
 [[101   9]
 [ 16  53]]
F1 score for XGBoost Classifier : 0.809160305344
Precision score for XGBoost Classifier : 0.854838709677
recall score for XGBoost Classifier : 0.768115942029
Wall time: 492 ms


## Creating kaggle submission file

In [127]:
def get_submission_file(model, filename):
    # converting to the matrix
    test_X = X_test_processed
    # make predictions
    predictions = model.predict(test_X)
    # submission dataframe
    df_submission = pd.DataFrame({'PassengerId': test_processed.index, 'Survived' : predictions})
    # submission file
    submission_data_path = os.path.join('I:\All_Projects\DataSciencePluralsight','submission_file')
    submission_file_path = os.path.join(submission_data_path, filename)
    # write to the file
    df_submission.to_csv(submission_file_path, index=False)

In [62]:
# get submission file
#get_submission_file(model_rf, 'byxgb2.csv')

### 9. Adaboost Classifier

In [57]:
from sklearn.ensemble import AdaBoostClassifier

In [60]:
model_ada=AdaBoostClassifier(random_state=0)

In [61]:
#help(model_ada)

In [63]:
%%time
parameters = {'n_estimators':[50,100,200],'learning_rate':[.4,.5,.6,.7],
              'algorithm':['SAMME', 'SAMME.R']
               }
grid_search = GridSearchCV(estimator = model_ada,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best Accuracy :',best_accuracy)
print('Best parameters:\n',best_parameters)

Best Accuracy : 0.828651685393
Best parameters:
 {'algorithm': 'SAMME', 'learning_rate': 0.5, 'n_estimators': 200}
Wall time: 1min


In [74]:
%%time
model_ada=AdaBoostClassifier(algorithm='SAMME',learning_rate=1.3,n_estimators=200)
model_ada.fit(X_train,y_train)
y_pred_ada=model_ada.predict(X_test)
kfscore=cross_val_score(estimator=model_ada,X=X_train,y=y_train,cv=3)
Avg_kfscore=kfscore.mean()
std_kfscore=kfscore.std()
print('Avg K-fold cross val score :',Avg_kfscore)
print('std of k-fold cross val score: \n',std_kfscore)
print('accuracy for AdaBoost Classifier :',accuracy_score(y_test,y_pred_ada))
print('confusion matrix for AdaBoost Classifier:\n',confusion_matrix(y_test,y_pred_ada))
print('F1 score for AdaBoost Classifier :',f1_score(y_test,y_pred_ada))
print('Precision score for AdaBoost Classifier :',precision_score(y_test,y_pred_ada))
print('recall score for AdaBoost Classifier :',recall_score(y_test,y_pred_ada))

Avg K-fold cross val score : 0.814653287475
std of k-fold cross val score: 
 0.0244259736468
accuracy for XGBoost Classifier : 0.826815642458
confusion matrix for XGBoost Classifier:
 [[93 17]
 [14 55]]
F1 score for XGBoost Classifier : 0.780141843972
Precision score for XGBoost Classifier : 0.763888888889
recall score for XGBoost Classifier : 0.797101449275
Wall time: 4.13 s


### 10. Bagging Classifier

In [75]:
from sklearn.ensemble import BaggingClassifier

In [90]:
model_bg=BaggingClassifier(random_state=0,verbose=0)

In [91]:
#help(model_bg)

In [95]:
%%time
parameters = {'n_estimators':[10,50,100,200],
              'oob_score':[True,False]
               }
grid_search = GridSearchCV(estimator = model_bg,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best Accuracy :',best_accuracy)
print('Best parameters:\n',best_parameters)

Best Accuracy : 0.801966292135
Best parameters:
 {'n_estimators': 200, 'oob_score': True}
Wall time: 29.7 s


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.7s finished


In [96]:
%%time
model_bg=BaggingClassifier(oob_score=True,n_estimators=200)
model_bg.fit(X_train,y_train)
y_pred_bg=model_bg.predict(X_test)
kfscore=cross_val_score(estimator=model_bg,X=X_train,y=y_train,cv=3)
Avg_kfscore=kfscore.mean()
std_kfscore=kfscore.std()
print('Avg K-fold cross val score :',Avg_kfscore)
print('std of k-fold cross val score: \n',std_kfscore)
print('accuracy for Bagging Classifier :',accuracy_score(y_test,y_pred_bg))
print('confusion matrix for Bagging Classifier:\n',confusion_matrix(y_test,y_pred_bg))
print('F1 score for Bagging Classifier :',f1_score(y_test,y_pred_bg))
print('Precision score for Bagging Classifier :',precision_score(y_test,y_pred_bg))
print('recall score for Bagging Classifier :',recall_score(y_test,y_pred_bg))

Avg K-fold cross val score : 0.810386601898
std of k-fold cross val score: 
 0.00615924574837
accuracy for Bagging Classifier : 0.815642458101
confusion matrix for Bagging Classifier:
 [[98 12]
 [21 48]]
F1 score for Bagging Classifier : 0.744186046512
Precision score for Bagging Classifier : 0.8
recall score for Bagging Classifier : 0.695652173913
Wall time: 6.85 s


### 11. Extra Tree Classifier

In [97]:
from sklearn.ensemble import ExtraTreesClassifier

In [100]:
model_et=ExtraTreesClassifier(random_state=0)

In [101]:
#help(model_et)

In [105]:
%%time
parameters = {'n_estimators':[10,50,100,200],
              'criterion':["gini","entropy"],
              'max_depth':[None,3,5,7,10]
               }
grid_search = GridSearchCV(estimator = model_et,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best Accuracy :',best_accuracy)
print('Best parameters:\n',best_parameters)

Best Accuracy : 0.830056179775
Best parameters:
 {'criterion': 'entropy', 'max_depth': 7, 'n_estimators': 200}
Wall time: 1min 10s


In [113]:
%%time
model_et=ExtraTreesClassifier(criterion='gini',n_estimators=100,max_depth=3)
model_et.fit(X_train,y_train)
y_pred_et=model_et.predict(X_test)
kfscore=cross_val_score(estimator=model_et,X=X_train,y=y_train,cv=3)
Avg_kfscore=kfscore.mean()
std_kfscore=kfscore.std()
print('Avg K-fold cross val score :',Avg_kfscore)
print('std of k-fold cross val score: \n',std_kfscore)
print('accuracy for ExtraTrees Classifier :',accuracy_score(y_test,y_pred_et))
print('confusion matrix for ExtraTrees Classifier:\n',confusion_matrix(y_test,y_pred_et))
print('F1 score for ExtraTrees Classifier :',f1_score(y_test,y_pred_et))
print('Precision score for ExtraTrees Classifier :',precision_score(y_test,y_pred_et))
print('recall score for ExtraTrees Classifier :',recall_score(y_test,y_pred_et))

Avg K-fold cross val score : 0.804837546833
std of k-fold cross val score: 
 0.03134840899
accuracy for ExtraTrees Classifier : 0.798882681564
confusion matrix for ExtraTrees Classifier:
 [[92 18]
 [18 51]]
F1 score for ExtraTrees Classifier : 0.739130434783
Precision score for ExtraTrees Classifier : 0.739130434783
recall score for ExtraTrees Classifier : 0.739130434783
Wall time: 1.84 s


### 12. GradientBoostingClassifier

In [114]:
from sklearn.ensemble import GradientBoostingClassifier

In [117]:
model_gbc=GradientBoostingClassifier(random_state=0)

In [118]:
#help(model_gbc)

In [119]:
%%time
parameters = {'n_estimators':[100,200],'learning_rate':[0.5,0.7,1.0,1.2],
              'loss':['deviance', 'exponential'],
              'max_depth':[3,5,7]
               }
grid_search = GridSearchCV(estimator = model_gbc,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print('Best Accuracy :',best_accuracy)
print('Best parameters:\n',best_parameters)

Best Accuracy : 0.820224719101
Best parameters:
 {'learning_rate': 0.5, 'loss': 'exponential', 'max_depth': 3, 'n_estimators': 100}
Wall time: 2min 38s


In [121]:
%%time
model_gbc=GradientBoostingClassifier(loss='exponential',learning_rate=0.5,n_estimators=100,max_depth=3)
model_gbc.fit(X_train,y_train)
y_pred_gbc=model_gbc.predict(X_test)
kfscore=cross_val_score(estimator=model_gbc,X=X_train,y=y_train,cv=3)
Avg_kfscore=kfscore.mean()
std_kfscore=kfscore.std()
print('Avg K-fold cross val score :',Avg_kfscore)
print('std of k-fold cross val score: \n',std_kfscore)
print('accuracy for GradientBoosting Classifier :',accuracy_score(y_test,y_pred_gbc))
print('confusion matrix for GradientBoosting Classifier:\n',confusion_matrix(y_test,y_pred_gbc))
print('F1 score for GradientBoosting Classifier :',f1_score(y_test,y_pred_gbc))
print('Precision score for GradientBoosting Classifier :',precision_score(y_test,y_pred_gbc))
print('recall score for GradientBoosting Classifier :',recall_score(y_test,y_pred_gbc))

Avg K-fold cross val score : 0.794980439433
std of k-fold cross val score: 
 0.0185166054631
accuracy for GradientBoosting Classifier : 0.804469273743
confusion matrix for GradientBoosting Classifier:
 [[94 16]
 [19 50]]
F1 score for GradientBoosting Classifier : 0.740740740741
Precision score for GradientBoosting Classifier : 0.757575757576
recall score for GradientBoosting Classifier : 0.724637681159
Wall time: 1.57 s


In [130]:
#why choose one model, when you can pick them all with voting classifier
#http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html
#removed models w/o attribute 'predict_proba' required for vote classifier and models with a 1.0 correlation to another model
from sklearn import svm, tree, linear_model, neighbors, naive_bayes, ensemble, discriminant_analysis, gaussian_process
from xgboost import XGBClassifier
from sklearn import model_selection
vote_est = [
    #Ensemble Methods: http://scikit-learn.org/stable/modules/ensemble.html
    ('ada', ensemble.AdaBoostClassifier()),
    ('bc', ensemble.BaggingClassifier()),
    ('etc',ensemble.ExtraTreesClassifier()),
    ('gbc', ensemble.GradientBoostingClassifier()),
    ('rfc', ensemble.RandomForestClassifier()),

    #Gaussian Processes: http://scikit-learn.org/stable/modules/gaussian_process.html#gaussian-process-classification-gpc
    ('gpc', gaussian_process.GaussianProcessClassifier()),
    
    #GLM: http://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
    ('lr', linear_model.LogisticRegressionCV()),
    
    #Navies Bayes: http://scikit-learn.org/stable/modules/naive_bayes.html
    ('bnb', naive_bayes.BernoulliNB()),
    ('gnb', naive_bayes.GaussianNB()),
    
    #Nearest Neighbor: http://scikit-learn.org/stable/modules/neighbors.html
    ('knn', neighbors.KNeighborsClassifier()),
    
    #SVM: http://scikit-learn.org/stable/modules/svm.html
    ('svc', svm.SVC(probability=True)),
    
    #xgboost: http://xgboost.readthedocs.io/en/latest/model.html
   ('xgb', XGBClassifier())

]


#Hard Vote or majority rules
vote_hard = ensemble.VotingClassifier(estimators = vote_est , voting = 'hard')
vote_hard_cv = model_selection.cross_validate(vote_hard, X=X_train, y=y_train, cv  = 3)
vote_hard.fit(X_train,y_train)

print("Hard Voting Training w/bin score mean: {:.2f}". format(vote_hard_cv['train_score'].mean()*100)) 
print("Hard Voting Test w/bin score mean: {:.2f}". format(vote_hard_cv['test_score'].mean()*100))
print("Hard Voting Test w/bin score 3*std: +/- {:.2f}". format(vote_hard_cv['test_score'].std()*100*3))
print('-'*10)


#Soft Vote or weighted probabilities
vote_soft = ensemble.VotingClassifier(estimators = vote_est , voting = 'soft')
vote_soft_cv = model_selection.cross_validate(vote_soft, X_train,y_train, cv  = 3)
vote_soft.fit(X_train,y_train)

print("Soft Voting Training w/bin score mean: {:.2f}". format(vote_soft_cv['train_score'].mean()*100)) 
print("Soft Voting Test w/bin score mean: {:.2f}". format(vote_soft_cv['test_score'].mean()*100))
print("Soft Voting Test w/bin score 3*std: +/- {:.2f}". format(vote_soft_cv['test_score'].std()*100*3))
print('-'*10)


Hard Voting Training w/bin score mean: 93.05
Hard Voting Test w/bin score mean: 82.73
Hard Voting Test w/bin score 3*std: +/- 7.11
----------
Soft Voting Training w/bin score mean: 94.03
Soft Voting Test w/bin score mean: 82.45
Soft Voting Test w/bin score 3*std: +/- 6.76
----------


In [125]:
#why choose one model, when you can pick them all with voting classifier
#http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html
#removed models w/o attribute 'predict_proba' required for vote classifier and models with a 1.0 correlation to another model
from sklearn import svm, tree, linear_model, neighbors, naive_bayes, ensemble, discriminant_analysis, gaussian_process
from xgboost import XGBClassifier
from sklearn import model_selection
vote_est = [
    #Ensemble Methods: http://scikit-learn.org/stable/modules/ensemble.html
    ('ada', model_ada),
    ('bc', model_bg),
    ('etc',model_et),
    ('gbc', model_gbc),
    ('rfc', model_rf),

        
    #GLM: http://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
    ('lr', model_lr),
    
    #Navies Bayes: http://scikit-learn.org/stable/modules/naive_bayes.html
    ('bnb', naive_bayes.BernoulliNB()),
    ('gnb', model_nb),
    
    #Nearest Neighbor: http://scikit-learn.org/stable/modules/neighbors.html
    ('knn', model_knn),
    
    #SVM: http://scikit-learn.org/stable/modules/svm.html
    ('svc', svm.SVC(probability=True)),
    
    #xgboost: http://xgboost.readthedocs.io/en/latest/model.html
   ('xgb', model_xgb)

]


#Hard Vote or majority rules
vote_hard = ensemble.VotingClassifier(estimators = vote_est , voting = 'hard')
vote_hard_cv = model_selection.cross_validate(vote_hard, X=X_train, y=y_train, cv  = 3)
vote_hard.fit(X_train,y_train)

print("Hard Voting Training w/bin score mean: {:.2f}". format(vote_hard_cv['train_score'].mean()*100)) 
print("Hard Voting Test w/bin score mean: {:.2f}". format(vote_hard_cv['test_score'].mean()*100))
print("Hard Voting Test w/bin score 3*std: +/- {:.2f}". format(vote_hard_cv['test_score'].std()*100*3))
print('-'*10)


#Soft Vote or weighted probabilities
vote_soft = ensemble.VotingClassifier(estimators = vote_est , voting = 'soft')
vote_soft_cv = model_selection.cross_validate(vote_soft, X_train,y_train, cv  = 3)
vote_soft.fit(X_train,y_train)

print("Soft Voting Training w/bin score mean: {:.2f}". format(vote_soft_cv['train_score'].mean()*100)) 
print("Soft Voting Test w/bin score mean: {:.2f}". format(vote_soft_cv['test_score'].mean()*100))
print("Soft Voting Test w/bin score 3*std: +/- {:.2f}". format(vote_soft_cv['test_score'].std()*100*3))
print('-'*10)


Hard Voting Training w/bin score mean: 90.03
Hard Voting Test w/bin score mean: 82.87
Hard Voting Test w/bin score 3*std: +/- 5.76
----------
Soft Voting Training w/bin score mean: 91.43
Soft Voting Test w/bin score mean: 82.59
Soft Voting Test w/bin score 3*std: +/- 6.76
----------


In [131]:
# get submission file
get_submission_file(vote_soft, 'votesoft2.csv')